version: '2.1'
services:
  jenkins:
    build: ./jenkins
    ports:
     - "2222:2222"
     - "8080:8080"
     - "8081:8081"
     - "9418:9418"
#  burgr:
#    build: ./burgr
  slave1:
    build: ./slave
    ports:
     - "2223:22"
  slave2:
    build: ./slave
    ports:
     - "2224:22"
